# Generated by Django 3.2.25 on 2024-12-15 06:31


from django.contrib.auth import get_user_model, models
from django.db import migrations



def create_super_user(apps, schema_editor):
    User: models.User = get_user_model()

    User.objects.create_superuser(
        username='admin',
        email='admin@admin.com',
        password='admin'
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_super_user)
    ]
